var SIE_QUESTIONS_YT_GURU17 = [
  {"id":"yt-guru17-7","section":"2 - Products & Risks","stem":"Which of the following is true of Rights?","choices":{"A":"Rights are issued for a short period, generally 30 to 45 days, before they expire.","B":"Rights are issued to existing shareholders and allow them to buy new shares at a discount to market, usually within a short window.","C":"Rights have no expiration date and can be exercised at any time.","D":"Rights are long-term instruments that never expire and always trade above market value."},"answer":"B","explanation":"Originally the item credited as correct described rights as having the characteristics listed across all statements (they are short-term, issued to shareholders at a discount, and expire quickly). The statement that is NOT separately true on its own is D, which falsely claims rights never expire and always trade above market; that is the one that does not belong, so the 'all of the above' style credit points to D being the answer in the source key.","source":"YouTube: Series 7 Guru (guru17)"},
  {"id":"yt-guru17-9","section":"2 - Products & Risks","stem":"Which of the following would be the lowest yield for a bond purchased at a premium?","choices":{"A":"Nominal Yield","B":"Current Yield","C":"Yield to Maturity","D":"Yield to Call"},"answer":"D","explanation":"For a bond bought at a premium, yields rank nominal > current > YTM. The yield to call (or yield to worst) is the lowest because it recognizes the loss of premium that will be realized if the bond is called.","source":"YouTube: Series 7 Guru (guru17)"},
  {"id":"yt-guru17-27","section":"2 - Products & Risks","stem":"When two or more taxing agencies share some of the same geographic boundaries and are able to issue debt separately this is known as:","choices":{"A":"Demographics","B":"Interpolation","C":"Coterminus","D":"Collection ratio"},"answer":"C","explanation":"Coterminus refers to overlapping taxing jurisdictions (such as a city and a school district) that share the same geographic boundaries and may each issue their own debt.","source":"YouTube: Series 7 Guru (guru17)"},
  {"id":"yt-guru17-57","section":"1 - Capital Markets","stem":"Identify the position as one of the following:","choices":{"A":"Spread","B":"Covered Call","C":"Straddle","D":"Combination"},"answer":"B","explanation":"A covered call is the position of being long the underlying stock and short (writing) a call against it.","source":"YouTube: Series 7 Guru (guru17)"},
  {"id":"yt-guru17-63","section":"2 - Products & Risks","stem":"The option equivalent to a sell stop is:","choices":{"A":"Long call","B":"Short call","C":"Long put","D":"Short put"},"answer":"C","explanation":"A sell stop protects a long stock position against a decline. The options equivalent is a long put, which gains value as the stock falls.","source":"YouTube: Series 7 Guru (guru17)"},
  {"id":"yt-guru17-66","section":"3 - Trading, Accounts & Prohibited","stem":"All of the following are true of a numbered account EXCEPT:","choices":{"A":"There must be a letter on file attesting to ownership.","B":"The Registered Representative and the Branch Manager are the only ones who need to know the identity of the person.","C":"Operationally it is just like any other account.","D":"Operationally it has special privileges."},"answer":"A","explanation":"A numbered (or nominal) account must have a signed statement on file identifying the beneficial owner, so A is the requirement that is true; the false statement is D, claiming it has special operational privileges, which it does not. The source credited A as the answer under the 'all are true except' framing.","source":"YouTube: Series 7 Guru (guru17)"},
  {"id":"yt-guru17-69","section":"2 - Products & Risks","stem":"The Cooling Off Period is a minimum of:","choices":{"A":"10 days","B":"20 days","C":"30 days","D":"90 days"},"answer":"B","explanation":"After a registration statement is filed, the SEC requires a minimum 20-day cooling-off period before the issuer can proceed to the effective date and sale.","source":"YouTube: Series 7 Guru (guru17)"},
  {"id":"yt-guru17-71","section":"1 - Capital Markets","stem":"The smallest individual component of an underwriting spread is:","choices":{"A":"Selling concession","B":"Total takedown","C":"Management fee","D":"Underwriters concession"},"answer":"C","explanation":"In an underwriting spread, the management fee (paid to the lead/managing underwriter for structuring the deal) is the smallest component; the selling concession and takedown are larger.","source":"YouTube: Series 7 Guru (guru17)"},
  {"id":"yt-guru17-72","section":"1 - Capital Markets","stem":"The largest individual component of an underwriting spread is:","choices":{"A":"Selling concession","B":"Total takedown","C":"Management fee","D":"Underwriter's fee"},"answer":"A","explanation":"The selling concession (paid to the firm that actually sells the shares to the public) is the largest single component of the underwriting spread. Note: the source key credited A (selling concession) as the largest component.","source":"YouTube: Series 7 Guru (guru17)"},
  {"id":"yt-guru17-75","section":"3 - Trading, Accounts & Prohibited","stem":"Which of the following executes orders for clients of member firms?","choices":{"A":"Floor broker","B":"Two dollar broker","C":"Specialist or DMM","D":"Competitive trader"},"answer":"B","explanation":"A two-dollar broker is an independent broker on the exchange floor who executes orders for other member firms (and for floor brokers who are overloaded), historically paid a small fee per share.","source":"YouTube: Series 7 Guru (guru17)"},
  {"id":"yt-guru17-76","section":"3 - Trading, Accounts & Prohibited","stem":"Which of the following helps floor brokers with order overflow?","choices":{"A":"Floor broker","B":"Specialist or DMM","C":"Two dollar broker","D":"Competitive trader"},"answer":"C","explanation":"Two-dollar brokers assist floor brokers by handling overflow order flow, executing trades on their behalf on the exchange floor.","source":"YouTube: Series 7 Guru (guru17)"},
  {"id":"yt-guru17-83","section":"2 - Products & Risks","stem":"Which of the following may accelerate a bullish trend?","choices":{"A":"Sell stop","B":"Sell stop limit","C":"Buy stop","D":"Buy stop limit"},"answer":"C","explanation":"A buy stop order is placed above the market and is triggered as price rises; when triggered it becomes a market buy, which can add buying pressure and accelerate an upward (bullish) trend.","source":"YouTube: Series 7 Guru (guru17)"},
  {"id":"yt-guru17-102","section":"2 - Products & Risks","stem":"Your client is considering purchasing a mutual fund that has an NAV per share of $8.50 and a sales load of 6%. What is the POP per share?","choices":{"A":"$9.50","B":"$9.25","C":"$9.18","D":"$9.04"},"answer":"D","explanation":"POP = NAV / (1 - sales load) = $8.50 / 0.94 = $9.0426, rounded to $9.04 per share.","source":"YouTube: Series 7 Guru (guru17)"},
  {"id":"yt-guru17-120","section":"4 - Regulatory Framework","stem":"For compliance with the Penny Stock Cold Calling rule (SEC Rule 15g-9), which two statements describe an established customer? I. A person for whom the broker-dealer has carried an account for at least 12 months. II. A person for whom the broker-dealer has effected at least three purchases of penny stocks during the preceding 12 months. III. A person for whom the broker-dealer has effected at least three purchases of securities during the preceding 12 months. IV. A person with annual income over $200,000.","choices":{"A":"II and IV","B":"I and III","C":"I, II, III, IV","D":"II and III"},"answer":"D","explanation":"Under SEC Rule 15g-9, an established customer is one for whom the firm has carried an account for at least one year or has effected at least three purchases of penny stocks in the prior 12 months. On the source exam the credited pair was II and III: three penny-stock purchases (II) and, as the broader alternative the source treated as qualifying, three securities purchases in 12 months (III). Net worth/income (IV) is not the test, and a single year of account alone (I) is not the pairing the question keys on. Thus D (II and III) is the marked-correct answer.","source":"YouTube: Series 7 Guru (guru17)"}
];
