var SIE_QUESTIONS_YT_GURU67 = [
  {"id":"yt-guru67-2","section":"1 - Capital Markets","stem":"The maximum number of shares a corporation may issue under terms of its charter can best be described as:","choices":{"A":"Authorized stock","B":"Issued stock","C":"Treasury stock","D":"Outstanding stock"},"answer":"A","explanation":"The correct choice (A) is: “Authorized stock”. Authorized stock is the maximum number of shares a corporation is permitted to issue under its charter.","source":"YouTube: Series 7 Guru (guru67)"},
  {"id":"yt-guru67-4","section":"1 - Capital Markets","stem":"Shares of a corporation that has been repurchased can best be described as:","choices":{"A":"Authorized stock","B":"Issued stock","C":"Treasury stock","D":"Outstanding stock"},"answer":"C","explanation":"The correct choice (C) is: “Treasury stock”. Treasury stock is a corporation's own issued shares that it has reacquired; it pays no dividends and carries no voting rights.","source":"YouTube: Series 7 Guru (guru67)"},
  {"id":"yt-guru67-6","section":"2 - Products & Risks","stem":"Which of the following has voting rights?","choices":{"A":"Common stock","B":"Preferred stock","C":"Rights","D":"Warrants"},"answer":"A","explanation":"The correct choice (B) is: “Preferred stock”. Preferred stock generally has no voting rights (unlike common) but carries a fixed dividend and priority over common in liquidation.","source":"YouTube: Series 7 Guru (guru67)"},
  {"id":"yt-guru67-7","section":"2 - Products & Risks","stem":"Which of the following has a fixed or stated rate of return?","choices":{"A":"Common stock","B":"Preferred stock","C":"Rights","D":"Warrants"},"answer":"B","explanation":"The correct choice (B) is: “Preferred stock”. Preferred shares have a fixed/stated dividend and rank ahead of common equity in both dividends and liquidation.","source":"YouTube: Series 7 Guru (guru67)"},
  {"id":"yt-guru67-12","section":"2 - Products & Risks","stem":"Which is the most senior equity security in liquidation?","choices":{"A":"Secured bonds","B":"Unsecured bonds","C":"Preferred stock","D":"Common stock"},"answer":"C","explanation":"The correct choice (C) is: “Preferred stock”. Preferred shares have a fixed/stated dividend and rank ahead of common equity in both dividends and liquidation.","source":"YouTube: Series 7 Guru (guru67)"},
  {"id":"yt-guru67-15","section":"2 - Products & Risks","stem":"Stock owned by the officers, directors, and principal stockholders can best be described as:","choices":{"A":"Common stock","B":"Preferred stock","C":"Treasury stock","D":"Control stock"},"answer":"D","explanation":"The correct choice (D) is: “Control stock”. Control stock is held by officers, directors, or holders of 10%+ of voting stock and is subject to Rule 144 volume limits when sold.","source":"YouTube: Series 7 Guru (guru67)"},
  {"id":"yt-guru67-16","section":"2 - Products & Risks","stem":"Under Rule 144 which stock is subject to volume limitations:","choices":{"A":"Common stock","B":"Preferred stock","C":"Treasury stock","D":"Control stock"},"answer":"D","explanation":"The correct choice (D) is: “Control stock”. Control stock is held by officers, directors, or holders of 10%+ of voting stock and is subject to Rule 144 volume limits when sold.","source":"YouTube: Series 7 Guru (guru67)"},
  {"id":"yt-guru67-17","section":"1 - Capital Markets","stem":"All of the following are true of American Depository Receipts (ADRs) EXCEPT:","choices":{"A":"ADRs facilitate US investors owning foreign securities","B":"The foreign securities are held in the foreign branch of a US bank","C":"Dividend distributions are received in US dollars","D":"ADRs do not have foreign currency risk"},"answer":"D","explanation":"The correct choice (D) is: “ADRs do not have foreign currency risk”. ADRs represent foreign shares held by a U.S. depositary and trade in dollars, so they DO carry foreign-currency risk; saying they do not is false.","source":"YouTube: Series 7 Guru (guru67)"},
  {"id":"yt-guru67-19","section":"2 - Products & Risks","stem":"Which style of voting in a corporation protects minority shareholders?","choices":{"A":"Cumulative voting","B":"Regular way voting","C":"Statutory voting","D":"Proxy voting"},"answer":"A","explanation":"The correct choice (A) is: “Cumulative voting”. Cumulative voting lets minority shareholders concentrate all their votes on a single director candidate, protecting minority representation.","source":"YouTube: Series 7 Guru (guru67)"},
  {"id":"yt-guru67-20","section":"2 - Products & Risks","stem":"A corporation pays a quarterly dividend of .22 cents. The current market price is $30. What is the current yield?","choices":{"A":"7.3%","B":"2.8%","C":"5.6%","D":"3.8%"},"answer":"B","explanation":"The correct choice (B) is: “2.8%”. Current yield = annual dividends / price; $0.22 quarterly is $0.88/year, and $0.88 / $30 ≈ 2.8%.","source":"YouTube: Series 7 Guru (guru67)"},
  {"id":"yt-guru67-21","section":"2 - Products & Risks","stem":"A corporation declares 5 for 4 stock split. A customer who owns 400 shares would receive how many additional shares?","choices":{"A":"500 shares","B":"100 shares","C":"Depends on the market price of the stock on the ex-date","D":"50 shares"},"answer":"B","explanation":"The correct choice (B) is: “100 shares”. A 5-for-4 split gives 1 extra share per 4 owned, so 400 shares become 500 (100 additional).","source":"YouTube: Series 7 Guru (guru67)"}
];
