SIE_QUESTIONS_YOUTUBE_ER3 = [
 {
  "id": "yt-ER3-",
  "section": "2 - Products & Risks",
  "stem": "Which of the following statements is true regarding common stock?",
  "choices": {
   "A": "Common stock typically offers fixed dividend payments.",
   "B": "Common stock shareholders have a residual claim to assets in a liquidation.",
   "C": "Common stock is a debt instrument representing a loan to the company.",
   "D": "Common stock shareholders do not have voting rights."
  },
  "answer": "B",
  "explanation": "Correct answer: Common stock shareholders have a residual claim to assets in a liquidation.",
  "source": "YouTube: Series 7 Guru (er3)"
 },
 {
  "id": "yt-ER3-",
  "section": "4 - Regulatory Framework",
  "stem": "A registered representative (RR) receives a complaint from a customer regarding a transaction. Under FINRA rules, what is the RR's primary responsibility with this complaint?",
  "choices": {
   "A": "Attempt to resolve the complaint directly with the customer.",
   "B": "Forward the complaint immediately to their supervisor or principal.",
   "C": "File the complaint directly with FINRA.",
   "D": "Ignore the complaint unless it is written and formally submitted."
  },
  "answer": "B",
  "explanation": "Correct answer: Forward the complaint immediately to their supervisor or principal.",
  "source": "YouTube: Series 7 Guru (er3)"
 },
 {
  "id": "yt-ER3-",
  "section": "3 - Trading, Accounts & Prohibited",
  "stem": "A married couple opens a brokerage account as Joint Tenants with Right of Survivorship (JTWROS). If one spouse dies, what happens to the assets in the account?",
  "choices": {
   "A": "The deceased spouse's share passes to their estate, subject to probate.",
   "B": "The surviving spouse automatically becomes the sole owner of the account.",
   "C": "The account is frozen until a court order dictates distribution.",
   "D": "The assets are split equally between the surviving spouse and the deceased spouse's heirs."
  },
  "answer": "B",
  "explanation": "Correct answer: The surviving spouse automatically becomes the sole owner of the account.",
  "source": "YouTube: Series 7 Guru (er3)"
 },
 {
  "id": "yt-ER3-",
  "section": "2 - Products & Risks",
  "stem": "An investor places an order to buy 100 shares of XYZ stock \"at market.\" This order will be executed:",
  "choices": {
   "A": "Only if the stock reaches a specified price or better.",
   "B": "Immediately at the best available price.",
   "C": "At the closing price of the trading day.",
   "D": "At a predetermined price set by the investor, regardless of market conditions."
  },
  "answer": "B",
  "explanation": "Correct answer: Immediately at the best available price.",
  "source": "YouTube: Series 7 Guru (er3)"
 },
 {
  "id": "yt-ER3-",
  "section": "2 - Products & Risks",
  "stem": "Which of the following characteristics is true of cumulative preferred stock?",
  "choices": {
   "A": "It has voting rights similar to common stock.",
   "B": "It allows investors to convert shares into common stock.",
   "C": "It accrues unpaid dividends that must be paid before common stockholders receive dividends.",
   "D": "Its dividend payments fluctuate based on the company's earnings."
  },
  "answer": "B",
  "explanation": "Correct answer: It allows investors to convert shares into common stock.",
  "source": "YouTube: Series 7 Guru (er3)"
 },
 {
  "id": "yt-ER3-",
  "section": "4 - Regulatory Framework",
  "stem": "An associated person uses confidential information obtained through their employment to trade securities for personal gain. This action is considered:",
  "choices": {
   "A": "A standard practice within the securities industry.",
   "B": "A violation of the insider trading rules.",
   "C": "Acceptable if the gains are reported to the firm.",
   "D": "Permissible as long as the information is not widely known."
  },
  "answer": "C",
  "explanation": "Correct answer: Acceptable if the gains are reported to the firm.",
  "source": "YouTube: Series 7 Guru (er3)"
 },
 {
  "id": "yt-ER3-",
  "section": "1 - Capital Markets",
  "stem": "How would an increase in the Consumer Price Index (CPI) likely affect the value of existing fixed-income securities, such as bonds?",
  "choices": {
   "A": "Their value would likely increase due to higher interest rates.",
   "B": "Their value would likely decrease due to higher interest rates.",
   "C": "Their value would remain unchanged, as bonds are not affected by inflation.",
   "D": "Their value would increase due to increased demand for fixed payments."
  },
  "answer": "B",
  "explanation": "Correct answer: Their value would likely decrease due to higher interest rates.",
  "source": "YouTube: Series 7 Guru (er3)"
 },
 {
  "id": "yt-ER3-",
  "section": "3 - Trading, Accounts & Prohibited",
  "stem": "Under the Uniform Gifts to Minors Act (UGMA) or Uniform Transfers to Minors Act (UTMA) accounts, who is responsible for paying taxes on the income generated by the account?",
  "choices": {
   "A": "The custodian of the account.",
   "B": "The minor.",
   "C": "The donor of the funds.",
   "D": "The broker-dealer holding the account."
  },
  "answer": "C",
  "explanation": "Correct answer: The donor of the funds.",
  "source": "YouTube: Series 7 Guru (er3)"
 },
 {
  "id": "yt-ER3-",
  "section": "1 - Capital Markets",
  "stem": "Which regulatory body is responsible for regulating municipal securities, including developing rules for municipal securities brokers and dealers?",
  "choices": {
   "A": "The Securities and Exchange Commission (SEC).",
   "B": "The Financial Industry Regulatory Authority (FINRA).",
   "C": "The Municipal Securities Rulemaking Board (MSRB).",
   "D": "The Federal Reserve Board (FRB)."
  },
  "answer": "C",
  "explanation": "Correct answer: The Municipal Securities Rulemaking Board (MSRB).",
  "source": "YouTube: Series 7 Guru (er3)",
  "needs_review": true
 },
 {
  "id": "yt-ER3-",
  "section": "2 - Products & Risks",
  "stem": "A key difference between an open-end management company (mutual fund) and a closed-end management company is that:",
  "choices": {
   "A": "Open-end funds trade on exchanges, while closed-end funds are redeemed by the fund.",
   "B": "Closed-end funds are continually offering new shares, while open-end funds have a fixed number of shares.",
   "C": "Open-end funds are priced at Net Asset Value (NAV), while closed-end funds can trade at a premium or discount to NAV.",
   "D": "Closed-end funds can only invest in debt securities, while open-end funds can invest in both stocks and bonds."
  },
  "answer": "C",
  "explanation": "Correct answer: Open-end funds are priced at Net Asset Value (NAV), while closed-end funds can trade at a premium or discount to NAV.",
  "source": "YouTube: Series 7 Guru (er3)"
 },
 {
  "id": "yt-ER3-",
  "section": "1 - Capital Markets",
  "stem": "Which of the following is primarily an \"interdealer\" market where unlisted securities are traded?",
  "choices": {
   "A": "The New York Stock Exchange (NYSE).",
   "B": "The Nasdaq Global Select Market.",
   "C": "The Over-the-Counter (OTC) market.",
   "D": "The Chicago Board Options Exchange (CBOE)."
  },
  "answer": "C",
  "explanation": "Correct answer: The Over-the-Counter (OTC) market.",
  "source": "YouTube: Series 7 Guru (er3)"
 },
 {
  "id": "yt-ER3-",
  "section": "4 - Regulatory Framework",
  "stem": "A firm's website, which is accessible to current and prospective customers, would be considered what type of communication under FINRA rules?",
  "choices": {
   "A": "Correspondence.",
   "B": "Institutional communication.",
   "C": "Retail communication.",
   "D": "Public appearance."
  },
  "answer": "C",
  "explanation": "Correct answer: Retail communication.",
  "source": "YouTube: Series 7 Guru (er3)"
 },
 {
  "id": "yt-ER3-",
  "section": "2 - Products & Risks",
  "stem": "Which type of risk affects a specific company or industry, but not necessarily the entire market?",
  "choices": {
   "A": "Systematic risk.",
   "B": "Interest rate risk.",
   "C": "Unsystematic risk.",
   "D": "Purchasing power risk."
  },
  "answer": "C",
  "explanation": "Correct answer: Unsystematic risk.",
  "source": "YouTube: Series 7 Guru (er3)",
  "needs_review": true
 },
 {
  "id": "yt-ER3-",
  "section": "2 - Products & Risks",
  "stem": "An Exchange Traded Note (ETN) is a type of unsecured debt security. This means that:",
  "choices": {
   "A": "ETNs offer principal protection and are guaranteed by a government entity.",
   "B": "The ETN's performance is tied to an underlying index, but the investor faces the credit risk of the issuer.",
   "C": "ETNs are always backed by a diversified portfolio of assets.",
   "D": "ETNs pay a fixed interest rate regardless of the underlying index performance."
  },
  "answer": "B",
  "explanation": "Correct answer: The ETN's performance is tied to an underlying index, but the investor faces the credit risk of the issuer.",
  "source": "YouTube: Series 7 Guru (er3)"
 },
 {
  "id": "yt-ER3-",
  "section": "3 - Trading, Accounts & Prohibited",
  "stem": "Which of the following accounts typically has a trustee who manages the assets for the benefit of a beneficiary?",
  "choices": {
   "A": "A cash account.",
   "B": "A margin account.",
   "C": "A trust account.",
   "D": "An individual retirement account (IRA)."
  },
  "answer": "C",
  "explanation": "Correct answer: A trust account.",
  "source": "YouTube: Series 7 Guru (er3)"
 },
 {
  "id": "yt-ER3-",
  "section": "3 - Trading, Accounts & Prohibited",
  "stem": "The Securities Investor Protection Corporation (SIPC) protects customer accounts against which of the following?",
  "choices": {
   "A": "Losses due to fluctuations in the market value of securities.",
   "B": "Fraudulent activities committed by the brokerage firm.",
   "C": "The failure of a broker-dealer, up to certain limits.",
   "D": "Investment losses caused by a registered representative's poor recommendations."
  },
  "answer": "C",
  "explanation": "Correct answer: The failure of a broker-dealer, up to certain limits.",
  "source": "YouTube: Series 7 Guru (er3)"
 },
 {
  "id": "yt-ER3-",
  "section": "1 - Capital Markets",
  "stem": "In a primary offering, a group of broker-dealers who collectively assist in the distribution of a new issue of securities is known as:",
  "choices": {
   "A": "A tender offer committee.",
   "B": "A stock exchange.",
   "C": "An underwriting syndicate.",
   "D": "A mutual fund."
  },
  "answer": "C",
  "explanation": "Correct answer: An underwriting syndicate.",
  "source": "YouTube: Series 7 Guru (er3)"
 },
 {
  "id": "yt-ER3-",
  "section": "1 - Capital Markets",
  "stem": "In a primary offering, a group of broker-dealers who collectively assist in the distribution of a new issue of securities is known as:",
  "choices": {
   "A": "A tender offer committee.",
   "B": "A stock exchange.",
   "C": "An underwriting syndicate.",
   "D": "A mutual fund."
  },
  "answer": "C",
  "explanation": "Correct answer: An underwriting syndicate.",
  "source": "YouTube: Series 7 Guru (er3)"
 },
 {
  "id": "yt-ER3-",
  "section": "1 - Capital Markets",
  "stem": "Which of the following statements is true regarding municipal bonds?",
  "choices": {
   "A": "The interest income from municipal bonds is always federally taxable.",
   "B": "Municipal bonds are generally considered riskier than corporate bonds.",
   "C": "The interest income from municipal bonds is often exempt from federal income tax.",
   "D": "Municipal bonds are typically issued by corporations to raise capital."
  },
  "answer": "C",
  "explanation": "Correct answer: The interest income from municipal bonds is often exempt from federal income tax.",
  "source": "YouTube: Series 7 Guru (er3)"
 },
 {
  "id": "yt-ER3-",
  "section": "3 - Trading, Accounts & Prohibited",
  "stem": "A registered representative repeatedly executes transactions in a customer's account that are excessive in size or frequency, given the customer's investment objectives. This prohibited practice is known as:",
  "choices": {
   "A": "Market manipulation.",
   "B": "Churning.",
   "C": "Front-running.",
   "D": "Free riding."
  },
  "answer": "B",
  "explanation": "Correct answer: Churning.",
  "source": "YouTube: Series 7 Guru (er3)",
  "needs_review": true
 },
 {
  "id": "yt-ER3-",
  "section": "3 - Trading, Accounts & Prohibited",
  "stem": "A registered representative repeatedly executes transactions in a customer's account that are excessive in size or frequency, given the customer's investment objectives. This prohibited practice is known as:",
  "choices": {
   "A": "Market manipulation.",
   "B": "Churning.",
   "C": "Front-running.",
   "D": "Free riding."
  },
  "answer": "B",
  "explanation": "Correct answer: Churning.",
  "source": "YouTube: Series 7 Guru (er3)",
  "needs_review": true
 },
 {
  "id": "yt-ER3-",
  "section": "3 - Trading, Accounts & Prohibited",
  "stem": "Regular way settlement for corporate equities and municipal bonds typically occurs on which day?",
  "choices": {
   "A": "Trade date (T).",
   "B": "Trade date plus one business day (T+1).",
   "C": "Trade date plus two business days (T+2).",
   "D": "Trade date plus three business days (T+3)."
  },
  "answer": "C",
  "explanation": "Correct answer: Trade date plus two business days (T+2).",
  "source": "YouTube: Series 7 Guru (er3)"
 },
 {
  "id": "yt-ER3-",
  "section": "1 - Capital Markets",
  "stem": "Which of the following statements is true regarding municipal bonds?",
  "choices": {
   "A": "The interest income from municipal bonds is always federally taxable.",
   "B": "Municipal bonds are generally considered riskier than corporate bonds.",
   "C": "The interest income from municipal bonds is often exempt from federal income tax.",
   "D": "Municipal bonds are typically issued by corporations to raise capital."
  },
  "answer": "C",
  "explanation": "Correct answer: The interest income from municipal bonds is often exempt from federal income tax.",
  "source": "YouTube: Series 7 Guru (er3)"
 },
 {
  "id": "yt-ER3-",
  "section": "4 - Regulatory Framework",
  "stem": "What is the primary purpose of Form U4, which must be completed by individuals registering with a FINRA member firm?",
  "choices": {
   "A": "To report customer complaints against the individual.",
   "B": "To apply for a securities license and disclose employment history and disciplinary actions.",
   "C": "To terminate an individual's registration with a firm.",
   "D": "To record continuing education requirements for registered representatives."
  },
  "answer": "B",
  "explanation": "Correct answer: To apply for a securities license and disclose employment history and disciplinary actions.",
  "source": "YouTube: Series 7 Guru (er3)"
 },
 {
  "id": "yt-ER3-",
  "section": "2 - Products & Risks",
  "stem": "An American Depositary Receipt (ADR) represents ownership in:",
  "choices": {
   "A": "A basket of domestic stocks traded on a foreign exchange.",
   "B": "A foreign company's shares, held in a U.S. bank.",
   "C": "A U.S. company's shares, held in a foreign bank.",
   "D": "A bond issued by a foreign government."
  },
  "answer": "B",
  "explanation": "Correct answer: A foreign company's shares, held in a U.S. bank.",
  "source": "YouTube: Series 7 Guru (er3)"
 },
 {
  "id": "yt-ER3-",
  "section": "1 - Capital Markets",
  "stem": "What does an inverted yield curve typically suggest about the economy?",
  "choices": {
   "A": "It predicts strong economic growth and rising inflation.",
   "B": "It suggests that short-term interest rates are lower than long-term interest rates, indicating investor optimism.",
   "C": "It indicates that short-term interest rates are higher than long-term interest rates, often preceding a recession.",
   "D": "It implies a stable economic outlook with moderate inflation."
  },
  "answer": "C",
  "explanation": "Correct answer: It indicates that short-term interest rates are higher than long-term interest rates, often preceding a recession.",
  "source": "YouTube: Series 7 Guru (er3)"
 },
 {
  "id": "yt-ER3-",
  "section": "4 - Regulatory Framework",
  "stem": "Which of the following retirement plans is typically established by employers and must comply with specific rules under the Employee Retirement Income Security Act (ERISA)?",
  "choices": {
   "A": "Individual Retirement Accounts (IRAs).",
   "B": "Roth IRAs.",
   "C": "Qualified plans, such as 401(k)s.",
   "D": "Non-qualified plans, such as deferred compensation plans."
  },
  "answer": "C",
  "explanation": "Correct answer: Qualified plans, such as 401(k)s.",
  "source": "YouTube: Series 7 Guru (er3)"
 },
 {
  "id": "yt-ER3-",
  "section": "3 - Trading, Accounts & Prohibited",
  "stem": "A registered representative makes a recommendation to a customer based solely on the customer's age. This action violates which FINRA rule?",
  "choices": {
   "A": "Communications with the Public rule.",
   "B": "Anti-Money Laundering rule.",
   "C": "Suitability rule.",
   "D": "Know Your Customer (KYC) rule."
  },
  "answer": "C",
  "explanation": "Correct answer: Suitability rule.",
  "source": "YouTube: Series 7 Guru (er3)"
 },
 {
  "id": "yt-ER3-",
  "section": "4 - Regulatory Framework",
  "stem": "Which of the following retirement plans is typically established by employers and must comply with specific rules under the Employee Retirement Income Security Act (ERISA)?",
  "choices": {
   "A": "Individual Retirement Accounts (IRAs).",
   "B": "Roth IRAs.",
   "C": "Qualified plans, such as 401(k)s.",
   "D": "Non-qualified plans, such as deferred compensation plans."
  },
  "answer": "C",
  "explanation": "Correct answer: Qualified plans, such as 401(k)s.",
  "source": "YouTube: Series 7 Guru (er3)"
 }
];
